INSERT INTO STUDENT (NOM, COGNOMS, BIRTH_DATE, NEWSLETTER) VALUES ('Joan', 'Petit', '2020-12-21', true);
INSERT INTO STUDENT (NOM, COGNOMS, BIRTH_DATE, NEWSLETTER) VALUES ('Joana', 'Petita', '2021-12-21', true);
INSERT INTO STUDENT (NOM, COGNOMS, BIRTH_DATE, NEWSLETTER) VALUES ('Gegant', 'Nobita', '2020-12-01', false);

INSERT INTO COURSE (TITULO) VALUES ('Informatica');
INSERT INTO COURSE (TITULO) VALUES ('Redes');
INSERT INTO COURSE (TITULO) VALUES ('DAW');